schemahero:
  enabled: true
image:
  repository: index.docker.io/vfarcic/cncf-demo
  tag: v0.0.1
ingress:
  host: cncf-demo.34.200.60.236.nip.io
  className: contour
db:
  enabled:
    crossplane:
      aws: true
  id: cncf-demo-db
  insecure: true
  size: small
otel:
  enabled: true
istio:
  enabled: true
  host: cncf-demo.34.226.47.201.nip.io
progressiveDelivery:
  enabled: true
  type: argo-rollouts
replicas: 0
