schemahero:
  enabled: true
image:
  repository: index.docker.io/vfarcic/cncf-demo
  tag: v0.0.2
ingress:
  host: cncf-demo.3.210.212.250.nip.io
  className: contour
db:
  enabled:
    crossplane:
      aws: true
  id: cncf-demo-db
  insecure: true
  size: small
istio:
  host: cncf-demo.44.208.195.106.nip.io
  enabled: true
replicas: 0
progressiveDelivery:
  enabled: true
  type: argo-rollouts
