gitOps:
  app: argocd
ingress:
  host: 34.203.2.152.nip.io
  classname: contour
image: index.docker.io/vfarcic/cncf-demo
tag: v0.0.1
templates: ytt
crossplane:
  destination: aws
production:
  azure:
    resourceGroup: dot-20240123133515
    location: eastus
  google:
    projectId: dot-20240911125241
hyperscaler: aws
secrets: eso
