- op: replace
  path: /spec/rules/0/host
  value: cncf-demo.54.235.211.220.nip.io
- op: replace
  path: /spec/tls/0/hosts/0
  value: cncf-demo.54.235.211.220.nip.io
- op: replace
  path: /spec/ingressClassName
  value: contour
