---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cncf-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/devopsparadox/cncf-demo.git
    targetRevision: HEAD
    path: yaml/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
